ALTER TABLE IF EXISTS provider_models_current
    DROP COLUMN IF EXISTS supports_tools;

DROP TABLE IF EXISTS tool_call_dead_letters CASCADE;
DROP TABLE IF EXISTS tool_results CASCADE;
DROP TABLE IF EXISTS tool_calls CASCADE;
DROP TABLE IF EXISTS session_events CASCADE;
DROP TABLE IF EXISTS session_turns CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
