from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "Axis",
    "AxisMember",
    "ClaimOrder",
    "ColumnType",
    "CompletionFilter",
    "CreatePoolRequest",
    "DbConfig",
    "DbRuntime",
    "DeletePoolRequest",
    "DeletePoolsByTokenRequest",
    "DeletePoolsByTokenResult",
    "DeletePoolsByTokenStatus",
    "GridCell",
    "InsertResult",
    "KeyColumn",
    "LlmPoolBackend",
    "LlmPoolBackendConfig",
    "LlmPoolBackendState",
    "LlmProcessFn",
    "LlmResponseStats",
    "LlmWorkerBackend",
    "PoolCreationBlockReason",
    "PoolCreationReadiness",
    "PoolCreationViolation",
    "PoolDeletionBlockReason",
    "PoolDeletionReadiness",
    "PoolDeletionResult",
    "PoolDeletionStatus",
    "PoolDeletionViolation",
    "PoolError",
    "PoolInspection",
    "PoolInspectionRequest",
    "PoolKeyEqClause",
    "PoolKeyFilter",
    "PoolKeyInClause",
    "PoolNotFoundError",
    "PoolProgress",
    "PoolReader",
    "PoolSample",
    "PoolSchema",
    "PoolSchemaError",
    "PoolStore",
    "PoolSummaryColumn",
    "RequestUpdate",
    "RoundRobinClaimer",
    "assess_pool_creation",
    "assess_pool_deletion",
    "create_pool",
    "delete_pool",
    "delete_pools_by_token",
    "discover_pools",
    "discover_pools_from_runtime",
    "drain_pool",
    "format_worker_progress_line",
    "inspect_pool",
    "make_llm_process_fn",
    "parse_response_stats",
    "pool_is_idle",
    "pool_summary_table",
    "sample_response_stats",
    "seed_grid",
    "seed_llm_grid",
    "print_pool_summary",
]

_EXPORT_MODULES = {
    "Axis": "dr_llm.pool.seed_grid",
    "AxisMember": "dr_llm.pool.seed_grid",
    "ClaimOrder": "dr_llm.pool.claim_strategy",
    "ColumnType": "dr_llm.pool.db",
    "CompletionFilter": "dr_llm.pool.completion_filter",
    "CreatePoolRequest": "dr_llm.pool.admin.creation",
    "DbConfig": "dr_llm.pool.db",
    "DbRuntime": "dr_llm.pool.db",
    "DeletePoolRequest": "dr_llm.pool.admin.deletion",
    "DeletePoolsByTokenRequest": "dr_llm.pool.admin.deletion",
    "DeletePoolsByTokenResult": "dr_llm.pool.admin.deletion",
    "DeletePoolsByTokenStatus": "dr_llm.pool.admin.deletion",
    "GridCell": "dr_llm.pool.seed_grid",
    "InsertResult": "dr_llm.pool.insert_result",
    "KeyColumn": "dr_llm.pool.db",
    "LlmPoolBackend": "dr_llm.pool.backend",
    "LlmPoolBackendConfig": "dr_llm.pool.backend",
    "LlmPoolBackendState": "dr_llm.pool.backend",
    "LlmProcessFn": "dr_llm.pool.backend",
    "LlmResponseStats": "dr_llm.pool.response_stats",
    "LlmWorkerBackend": "dr_llm.pool.backend",
    "PoolCreationBlockReason": "dr_llm.pool.admin.creation",
    "PoolCreationReadiness": "dr_llm.pool.admin.creation",
    "PoolCreationViolation": "dr_llm.pool.admin.creation",
    "PoolDeletionBlockReason": "dr_llm.pool.admin.deletion",
    "PoolDeletionReadiness": "dr_llm.pool.admin.deletion",
    "PoolDeletionResult": "dr_llm.pool.admin.deletion",
    "PoolDeletionStatus": "dr_llm.pool.admin.deletion",
    "PoolDeletionViolation": "dr_llm.pool.admin.deletion",
    "PoolError": "dr_llm.pool.errors",
    "PoolInspection": "dr_llm.pool.admin.inspection",
    "PoolInspectionRequest": "dr_llm.pool.admin.inspection",
    "PoolKeyEqClause": "dr_llm.pool.db",
    "PoolKeyFilter": "dr_llm.pool.db",
    "PoolKeyInClause": "dr_llm.pool.db",
    "PoolNotFoundError": "dr_llm.pool.errors",
    "PoolProgress": "dr_llm.pool.pool_progress",
    "PoolReader": "dr_llm.pool.reader",
    "PoolSample": "dr_llm.pool.pool_sample",
    "PoolSchema": "dr_llm.pool.db",
    "PoolSchemaError": "dr_llm.pool.errors",
    "PoolStore": "dr_llm.pool.pool_store",
    "PoolSummaryColumn": "dr_llm.pool.summary",
    "RequestUpdate": "dr_llm.pool.store_ops.request_update",
    "RoundRobinClaimer": "dr_llm.pool.claim_strategy",
    "assess_pool_creation": "dr_llm.pool.admin.creation",
    "assess_pool_deletion": "dr_llm.pool.admin.deletion",
    "create_pool": "dr_llm.pool.admin.creation",
    "delete_pool": "dr_llm.pool.admin.deletion",
    "delete_pools_by_token": "dr_llm.pool.admin.deletion",
    "discover_pools": "dr_llm.pool.admin.discovery",
    "discover_pools_from_runtime": "dr_llm.pool.admin.discovery",
    "drain_pool": "dr_llm.pool.progress",
    "format_worker_progress_line": "dr_llm.pool.progress",
    "inspect_pool": "dr_llm.pool.admin.inspection",
    "make_llm_process_fn": "dr_llm.pool.backend",
    "parse_response_stats": "dr_llm.pool.response_stats",
    "pool_is_idle": "dr_llm.pool.progress",
    "pool_summary_table": "dr_llm.pool.summary",
    "sample_response_stats": "dr_llm.pool.response_stats",
    "seed_grid": "dr_llm.pool.seed_grid",
    "seed_llm_grid": "dr_llm.pool.seed_grid",
    "print_pool_summary": "dr_llm.pool.summary",
}


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value
