from dr_llm.llm.providers.impls.anthropic.capabilities import (
    ANTHROPIC_BUDGET_MAX_TOKENS,
    ANTHROPIC_BUDGET_MIN_TOKENS,
)
from dr_llm.llm.providers.impls.anthropic.families import (
    ANTHROPIC_ADAPTIVE_THINKING_SUPPORTED,
    ANTHROPIC_BUDGET_THINKING_SUPPORTED,
)

ANTHROPIC_THINKING_MIN_BUDGET_TOKENS = ANTHROPIC_BUDGET_MIN_TOKENS
ANTHROPIC_THINKING_MAX_BUDGET_TOKENS = ANTHROPIC_BUDGET_MAX_TOKENS

__all__ = [
    "ANTHROPIC_ADAPTIVE_THINKING_SUPPORTED",
    "ANTHROPIC_BUDGET_THINKING_SUPPORTED",
    "ANTHROPIC_THINKING_MAX_BUDGET_TOKENS",
    "ANTHROPIC_THINKING_MIN_BUDGET_TOKENS",
]
